import markdown
import os
import re
from bs4 import BeautifulSoup

def group_images_in_rows(md_content):
    """Group images in rows of 3 for better layout."""
    img_pattern = r'!\[.*?\]\((.*?)\)'
    lines = md_content.split('\n')
    new_lines = []
    buffer = []

    for line in lines:
        match = re.match(img_pattern, line.strip())
        if match:
            img_src = match.group(1)
            buffer.append(f'<img src="{img_src}" alt="" />')
            if len(buffer) == 3:
                new_lines.append('<div class="image-row">\n' + '\n'.join(buffer) + '\n</div>')
                buffer = []
        else:
            if buffer:
                new_lines.append('<div class="image-row">\n' + '\n'.join(buffer) + '\n</div>')
                buffer = []
            new_lines.append(line)
    if buffer:
        new_lines.append('<div class="image-row">\n' + '\n'.join(buffer) + '\n</div>')
    return '\n'.join(new_lines)

def extract_first_page_content(first_page_html_path):
    """Extract the content from the first page HTML generated by first_page.py."""
    try:
        with open(first_page_html_path, 'r', encoding='utf-8') as f:
            html_content = f.read()
        
        # Parse the HTML to extract the body content and styles
        soup = BeautifulSoup(html_content, 'html.parser')
        
        # Extract styles
        style_tag = soup.find('style')
        first_page_styles = style_tag.get_text() if style_tag else ""
        
        # Extract body content (everything inside body tag)
        body_tag = soup.find('body')
        if body_tag:
            first_page_body = str(body_tag)
            # Remove the <body> and </body> tags, keep only the content
            first_page_body = re.sub(r'^<body[^>]*>', '', first_page_body)
            first_page_body = re.sub(r'</body>$', '', first_page_body)
        else:
            # If no body tag, take everything except style
            if style_tag:
                style_tag.decompose()
            first_page_body = str(soup)
        
        return first_page_body.strip(), first_page_styles
    
    except Exception as e:
        print(f"Error reading first page HTML: {e}")
        return "", ""

def create_integrated_html(first_page_html_path, remaining_pages_md_path, css_file_path, output_html_path, image_file_path):
    """Create integrated HTML with first page from first_page.py and remaining pages from markdown."""
    
    # Hardcoded footer content
    footer_content = """
Advanced Energy (AE) has devoted more than three decades to perfecting power for its global customers. AE designs and manufactures highly engineered, precision power conversion, measurement and control solutions for mission-critical applications and processes.

Our products enable customer innovation in complex applications for a wide range of industries including semiconductor equipment, industrial, manufacturing, telecommunications, data center computing, and medical. With deep applications know-how and responsive service and support across the globe, we build collaborative partnerships to meet rapid technological developments, propel growth for our customers, and innovate the future of power.

For international contact information, visit advancedenergy.com.

powersales@aei.com (Sales Support)  
productsupport.ep@aei.com (Technical Support)  +1 888 412 7832

Specifications are subject to change without notice. Not responsible for errors or omissions. ©2020 Advanced Energy Industries, Inc. All rights reserved. Advanced Energy®, and AE® are U.S. trademarks of Advanced Energy Industries, Inc."""
    
    # Extract first page content and styles
    first_page_content, first_page_styles = extract_first_page_content(first_page_html_path)
    
    if not first_page_content:
        print("Warning: Could not extract first page content. Using fallback.")
        first_page_content = "<p>First page content could not be loaded.</p>"
    
    # Read the remaining pages Markdown file
    remaining_pages_content = ""
    if os.path.exists(remaining_pages_md_path):
        with open(remaining_pages_md_path, 'r', encoding='utf-8') as md_file:
            remaining_pages_content = md_file.read()
        
        # Remove the specified text from the bottom of Markdown content
        text_to_remove = r"""For international contact information,.*?\bAdvanced Energy Industries, Inc\.""".strip()
        remaining_pages_content = re.sub(
            rf'{text_to_remove}\s*$',
            '',
            remaining_pages_content,
            flags=re.DOTALL | re.MULTILINE
        ).strip()
        
        # Group images in rows before converting to HTML
        remaining_pages_grouped = group_images_in_rows(remaining_pages_content)
        
        # Convert Markdown to HTML
        remaining_pages_html = markdown.markdown(remaining_pages_grouped, extensions=['extra', 'codehilite'])
    else:
        remaining_pages_html = "<p>No remaining pages found.</p>"
    
    # Convert footer to HTML
    footer_html = markdown.markdown(footer_content, extensions=['extra', 'codehilite'])
    
    # Read the original CSS file
    css_content = ""
    if os.path.exists(css_file_path):
        with open(css_file_path, 'r', encoding='utf-8') as css_file:
            css_content = css_file.read()
    
    # Extract page title from first page content
    soup = BeautifulSoup(first_page_content, 'html.parser')
    h1_tag = soup.find('h1')
    page_title = h1_tag.get_text().strip() if h1_tag else "Technical Reference Note"
    
    # Combine CSS from both sources (original CSS + first page styles)
    combined_css = css_content
    if first_page_styles:
        combined_css += "\n\n/* First Page Specific Styles */\n" + first_page_styles
    
    # Create the complete integrated HTML
    html_output = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{page_title}</title>
    <style>
{combined_css}
    </style>
</head>
<body>
<!-- First Page Section (Generated by first_page.py) -->
<div class="section first-page-section">
    {first_page_content}
</div>

<!-- Remaining Pages Section -->
<div class="section remaining-pages-section">
    <header style="position: relative; min-height: 80px;" class="header">
        <span style="position: absolute; left: 30px; top: 50px; color: #004080; font-weight: bold; font-size: 1.2em;">TECHNICAL REFERENCE NOTE</span>
        <img src="{image_file_path}" alt="Header Image" style="position: absolute; top: 0; right: 50px; max-width: 700px;">
    </header>
    <main>
        {remaining_pages_html}
    </main>
</div>

<!-- Footer Section -->
<div class="section footer-section">
    <h2 align="center">ABOUT ADVANCED ENERGY</h2>
    <footer class="footer">
        {footer_html}
    </footer>
</div>
</body>
</html>"""
    
    # Write the output to an HTML file
    with open(output_html_path, 'w', encoding='utf-8') as html_file:
        html_file.write(html_output)
    
    print(f"Integrated HTML file generated successfully: {output_html_path}")

def main():
    """Main function to run the integrated HTML generation."""
    # File paths
    first_page_html_path = "first_page_html.html"  # Generated by first_page.py
    remaining_pages_md_path = "remaining_pages.md"
    css_file_path = "pdf_styles.css"
    output_html_path = "integrated_output.html"
    image_file_path = "advance_energy.png"  # Path to the header image
    
    # Check if required files exist
    missing_files = []
    if not os.path.exists(first_page_html_path):
        missing_files.append(first_page_html_path)
    if not os.path.exists(remaining_pages_md_path):
        missing_files.append(remaining_pages_md_path)
    if not os.path.exists(css_file_path):
        missing_files.append(css_file_path)
    if not os.path.exists(image_file_path):
        missing_files.append(image_file_path)
    
    if missing_files:
        print("Error: The following required files are missing:")
        for file in missing_files:
            print(f"  - {file}")
        print("\nPlease ensure all files exist before running the integration.")
        return False
    
    try:
        create_integrated_html(
            first_page_html_path, 
            remaining_pages_md_path, 
            css_file_path, 
            output_html_path, 
            image_file_path
        )
        return True
    except Exception as e:
        print(f"Error during integration: {str(e)}")
        return False

if __name__ == "__main__":
    success = main()
    if success:
        print("Integration completed successfully!")
    else:
        print("Integration failed. Please check the errors above.")